from util.custom_enum import PlayerSide

CHARACTERS = [
    {
        'name': 'Lightning',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (-15, -73),

                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-160, -73),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.LEFT,
    },
    {
        'name': 'Cloud',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (-25, -32),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-52, -32),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.LEFT,
    },
    {
        'name': 'Tidus',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (0, -31),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-70, -31),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.RIGHT,
    },
    {
        'name': 'Firion',

        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (3, -27),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-34, -27),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.RIGHT,
    },
    {
        'name': 'Cecil',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (-30, -44),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-127, -44),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.LEFT,
    },
    {
        'name': 'Bartz',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (-13, -21),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-140, -21),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.RIGHT,
    },
    {
        'name': 'Zidane',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (-1, -20),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-50, -20),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.RIGHT,
    },
    {
        'name': 'Tera',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (0, 2),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-127, 2),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.LEFT,
    },
    {
        'name': 'Noctis',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (-139, -50),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-78, -50),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.LEFT,
    },
    {
        'name': 'Squall',
        'off_set': {
            'left':
            {
                'idle': (0, 0),
                'attack': (-10, -9),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
            'right':        {
                'idle': (0, 0),
                'attack': (-80, -9),
                'magic_attack': (0, 0),
                'magic_standby': (0, 0),
                'attack_standby': (0, 0),
                'limit_break': (0, 0),
                'dying': (0, 0),
                'dead': (0, 0),
                'move': (0, 0),
                'jump': (0, 0),
            },
        },
        'side': PlayerSide.LEFT,
    },
]
